name: Build and Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd website 
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          sudo gem install bundler
          bundle update
          make build

  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check links
        run: |
          cd website
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          sudo gem install bundler
          bundle update
          make check_links || make check_links || make check_links

  check-media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check media
        run: |
          cd website
          DIR=$(pwd)
          [ ! -f "$DIR/images" ]
          [ ! -f "$DIR/figures" ]
          [ ! -f "$DIR/icons" ]
